name: Setup Neon Database

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpx prisma generate

      - name: Validate Environment Variables
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "❌ DATABASE_URL is not set!"
            exit 1
          fi
          echo "✅ DATABASE_URL is set correctly."

      - name: Show DATABASE_URL value
        run: |
          echo "Using DATABASE_URL:"
          echo "${{ secrets.DATABASE_URL }}"


      - name: Run Database Setup
        run: node scripts/complete-setup.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy Application
        run: |
          echo "🚀 Starting deployment..."
          pnpm run build
          echo "✅ Application built successfully."
          echo "ℹ️ To start the application, run 'pnpm start'"
