name: Setup Neon Database

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpx prisma generate

      - name: Show DATABASE_URL value
        run: |
          echo "Using DATABASE_URL:"
          echo "$DATABASE_URL"

      - name: Run Database Setup
        run: node scripts/complete-setup.js
        env:
          DATABASE_URL: $DATABASE_URL

      - name: Validate Environment Variables
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL is not set!"
            exit 1
          fi
          echo "Environment variables validated successfully."

      - name: Deploy Application
        run: |
          echo "Starting deployment..."
          pnpm run build
          echo "Application built successfully."
          echo "To start the application, run 'pnpm start'"
          echo "Deployment completed successfully."
